# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd48195f287c48291b8f4574036be272f3a24a80e87547610df93e2e017947434ce2e2746c2539bb1c3a0444d075a2ad8ac1f0ce715495c8fe6a69b0d6045521

test:
  secret_key_base: cd262f3afa2f1fe1221ef549736554b9480c0aaa1a6e64f6eec4ed2d8e2e9076e8c9003d8a03f5281f341aef8f1e1e64387904849a903dcc908a84446f495006

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
